### ISSUE TITLE
Adicionar componente novos casos

### ISSUE THREAD

**Issue by santanacostamarco** [hackcovid-br/rt-app#21]
https://www.figma.com/file/HlbZ451tRc2rl03pQS3Phj/Wire---HC?node-id=0%3A1

Criar o componente de novos casos de acordo com o layout.

![image](https://user-images.githubusercontent.com/41493938/84827697-38a1c780-affb-11ea-9277-b110dd57be59.png)

**Comment by Joaovsa7** [comment]
Movi para o backlog porque estavamos esperando um novo design.
